name: Update JSONs

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests

      - name: Run script
        run: python fetch.py

      - name: Commit scraped JSON
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Update JSONs"  || exit 0
          git push
